PAYLSQUAD3-1218 : Créer/Editer le contrat
PaylinePaymentMethod/payment-method-carrefour-banque-nx pull request #1
Opened 2021-09-17 10:22 UTC by pesublet

2021-09-17 13:34 UTC, thomasmonext requested changes

2021-09-17 13:34 UTC, thomasmonext commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/impl/ConfigurationServiceImpl.java
> +            if (minDecimal > maxDecimal) {
" >= ", a réfléchir si c'est ça doit etre inclusif ou pas.

2021-09-17 13:34 UTC, thomasmonext commented on src/main/java/com/payline/payment/carrefour/banque/nx/utils/PluginUtils.java
> +    public static String extractBanks(String s) {
Je pense que `extract` et `extractBanks` ne sont pas nécessaire, peut-être que dautres éléments peuvent etre supprimés.

2021-09-23 15:16 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/impl/ConfigurationServiceImpl.java
> +            if (minDecimal > maxDecimal) {
le code va être supprimé car plus de min max :)

2021-09-23 16:01 UTC, pesublet commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.2.1-all.zip
passage à gradle 7.2

2021-10-04 12:30 UTC, merged