PAYLANO-6866
PaylinePaymentMethod/payment-method-carrefour-banque-nx pull request #19
Opened 2022-05-09 12:42 UTC by JeremyMattio

Prise en compte dans le cas d'un Refund du montant déjà validé (capturé) et non du montant autorisé.

2022-05-11 08:58 UTC, thomasmonext requested changes

2022-05-11 08:58 UTC, thomasmonext commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/CancelationRequestMapper.java
>          final BigInteger canceledAmount = resetRequest.getAmount().getAmountInSmallestUnit();
Pourquoi il n'y a pas le meme calcul avec la balance du reset ?

2022-05-11 13:01 UTC, JeremyMattio commented on src/main/java/com/payline/payment/carrefour/banque/nx/business/impl/CirceoPaymentBusinessImpl.java
> +        return switch (cancelResponseStatus) {
oups

2022-05-12 13:06 UTC, JeremyMattio commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/CancelationRequestMapper.java
> +        final BigInteger canceledAmount = refundRequest.getAmount().getAmountInSmallestUnit();
Done

2022-05-12 13:06 UTC, JeremyMattio commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/CancelationRequestMapper.java
>          final BigInteger canceledAmount = resetRequest.getAmount().getAmountInSmallestUnit();
Done

2022-05-16 07:47 UTC, JeremyMattio commented on gradle.properties
> +paymentMethodApiVersion = 1.20-JMO2-SNAPSHOT
yes je l'ai mis en version SNAPSHOT.

2022-05-16 11:52 UTC, merged