PAYLSQUAD3-1247 CARREFOUR_BANQUE_NX DoReset
PaylinePaymentMethod/payment-method-carrefour-banque-nx pull request #8
Opened 2021-10-15 13:23 UTC by Monext-kkaddour

2021-10-18 08:49 UTC, pesublet requested changes

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/bean/request/CancelationRequest.java
> +    String cancelationType;
Tu peux utiliser l'enum ici plutôt que le type String

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/bean/request/CancelationRequest.java
> +    Float newFinancedAmount;
j'aurais plutôt mis un type primitif car le champ est requis

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/bean/request/CancelationRequest.java
> +    Float canceledAmount;
j'aurais plutôt mis un type primitif car le champ est requis

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/bean/request/CancelationRequest.java
> +    String miscData;
En avance de phase, tu peux mettre Map<String, Object> miscData; (cf https://github.com/PaylinePaymentMethod/payment-method-carrefour-banque-nx/pull/7/files)

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/bean/request/CancelationRequest.java
> +    Cart cart;
ici tu recycles un objet qui n'est pas le bon et qui contient d'autres champs hors API circeo. Vu qu'on ne dois pas l'envoyer, peut être que je l'aurais supprimé plutôt que d'envoyer un champ erroné. Ou bien créer un CancelationCart, mais c'est vrai que c'est pas très utile pour le moment vu qu'on ne l'utilise pas

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/bean/response/CancelationResponse.java
> +    String cancelationRequestState;
Utilise plutôt le type enum

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/CancelationRequestMapper.java
> +        if(newFinancedAmount > 0){
checkstyle, n'oublie pas les espaces ! "if (", ") {"

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/CancelationRequestMapper.java
> +        final Currency currency=resetRequest.getOrder().getAmount().getCurrency();
espaces autour du "="

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/CancelationRequestMapper.java
> +        final BigInteger cancledAmount = resetRequest.getAmount().getAmountInSmallestUnit();
typo canceled

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/CancelationRequestMapper.java
> +        String newFinancedAmountCalculeted = AmountMapper.INSTANCE.mapAmount(newFinancedAmount);
typo newFinancedAmountCalculeted => newFinancedAmountCalculated

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/CancelationRequestMapper.java
> +@Mapper(uses = {OrderMapper.class, AmountMapper.class})
pas besoin des uses ici je pense

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/business/impl/CirceoPaymentService.java
> +    public CancelationResponse doCancel(FinancingRequestToCancel financingRequest, String financingId, PartnerConfiguration partnerConfiguration) throws HttpErrorException{
espace avant {

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/impl/ResetServiceImpl.java
> +@Log4j2
saut de ligne avant les annotations

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/impl/ResetServiceImpl.java
> +                  return ResetResponseSuccess.ResetResponseSuccessBuilder
pas de return intermédiaire, un seul return à la fin

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/impl/ResetServiceImpl.java
> +                    .withFailureCause(FailureCause.INVALID_DATA)
regarde la spec de Nico, on a un type d'erreur différent suivant les states

2021-10-18 08:49 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/impl/ResetServiceImpl.java
> +        }catch (final HttpErrorException e) {
espace après  le }

2021-10-18 09:00 UTC, thomasmonext commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/impl/ResetServiceImpl.java
> +            if (CancelationRequestState.DONE.name().equals(cancelResponseStatus)) {
comparer les énum directement

2021-10-18 09:02 UTC, thomasmonext commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/impl/ResetServiceImpl.java
> +            }
if ... else ... avec le return à la fin

2021-10-18 09:31 UTC, thomasmonext commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/impl/ResetServiceImpl.java
> +            resetResponse = ResetResponseFailure.ResetResponseFailureBuilder.aResetResponseFailure()
Gestion des erreurs à revoir.
Il faut qu'on en discute avec PES.

2021-10-19 09:46 UTC, Monext-kkaddour commented on src/main/java/com/payline/payment/carrefour/banque/nx/bean/request/CancelationRequest.java
> +    Float canceledAmount;
DONE

2021-10-19 12:26 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/CancelationRequestMapper.java
> +@Mapper(uses = {OrderMapper.class, AmountMapper.class})
vu avec Kais, ça compile pas sans, on laisse !

2021-10-20 06:24 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/HeaderSimpleMapper.java
> +        return new SimpleDateFormat(Constants.DATE_TIME_FORMAT).format(new Date());
On a testé avec Kais, sonar remonte une erreur si on fait comme ça car SimpleDateFormat n'est pas thread safe

2021-10-20 06:25 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/CancelationRequestMapper.java
> +        if(newFinancedAmount > 0) {
il manque un petit espace ici

2021-10-20 06:28 UTC, pesublet commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/impl/ResetServiceImpl.java
> +                        .withFailureCause(FailureCause.COMMUNICATION_ERROR)
Du coup le FailureCause serait plutôt INVALID_DATA ici je pense. Tu es OK @thomasmonext ?  
Est-ce que tu pourrais aussi modifier au passage : com/payline/payment/carrefour/banque/nx/service/impl/PaymentServiceImpl.java:61 et com/payline/payment/carrefour/banque/nx/service/impl/PaymentWithRedirectionServiceImpl.java:49 ?

2021-10-20 07:12 UTC, Monext-kkaddour commented on src/main/java/com/payline/payment/carrefour/banque/nx/mapper/CancelationRequestMapper.java
> +        if(newFinancedAmount > 0) {
DONE

2021-10-20 07:12 UTC, Monext-kkaddour commented on src/main/java/com/payline/payment/carrefour/banque/nx/service/impl/ResetServiceImpl.java
> +                        .withFailureCause(FailureCause.COMMUNICATION_ERROR)
DONE

2021-10-20 07:54 UTC, merged